<?php
return [
    // Common
    'app_name'          => 'SL 인더스트리 급여',
    'dashboard'         => '대시보드',
    'employees'         => '직원',
    'attendance'        => '근태',
    'payroll'           => '급여',
    'reports'           => '보고서',
    'settings'          => '설정',
    'logout'            => '로그아웃',
    'save'              => '저장',
    'cancel'            => '취소',
    'edit'              => '편집',
    'delete'            => '삭제',
    'view'              => '보기',
    'add'               => '추가',
    'search'            => '검색',
    'filter'            => '필터',
    'export'            => '내보내기',
    'print'             => '인쇄',
    'download'          => '다운로드',
    'upload'            => '업로드',
    'active'            => '활성',
    'inactive'          => '비활성',
    'status'            => '상태',
    'actions'           => '작업',
    'loading'           => '로딩 중...',
    'confirm_delete'    => '이 레코드를 삭제하시겠습니까?',
    'success'           => '성공',
    'error'             => '오류',
    'no_records'        => '레코드 없음',

    // Auth
    'login'             => '로그인',
    'username'          => '사용자명',
    'password'          => '비밀번호',
    'login_btn'         => '로그인',
    'login_title'       => '관리자 로그인',
    'login_subtitle'    => '급여 관리 시스템',
    'invalid_login'     => '잘못된 사용자명 또는 비밀번호',
    'account_locked'    => '계정이 잠겼습니다. 나중에 다시 시도하세요.',

    // Dashboard
    'total_employees'   => '전체 직원',
    'active_employees'  => '재직 직원',
    'payroll_this_month'=> '이번 달 급여',
    'total_overtime'    => '총 초과근무',
    'total_advances'    => '총 선급금',
    'due_salaries'      => '미지급 급여',
    'recent_payroll'    => '최근 급여',
    'attendance_summary'=> '근태 요약',

    // Employees
    'employee_id'       => '직원 ID',
    'employee_name'     => '직원 이름',
    'employee_type'     => '직원 유형',
    'korean_employee'   => '한국인 직원',
    'foreign_employee'  => '외국인 직원',
    'phone'             => '전화번호',
    'email'             => '이메일',
    'nationality'       => '국적',
    'date_of_birth'     => '생년월일',
    'join_date'         => '입사일',
    'bank_name'         => '은행명',
    'account_number'    => '계좌번호',
    'account_holder'    => '예금주',
    'hourly_rate'       => '시간당 급여',
    'tax_rate'          => '세율 (%)',
    'add_employee'      => '직원 추가',
    'edit_employee'     => '직원 편집',
    'employee_profile'  => '직원 프로필',
    'personal_info'     => '개인 정보',
    'banking_info'      => '금융 정보',
    'documents'         => '서류',
    'emergency_contact' => '비상 연락처',
    'notes'             => '비고',
    'id_card_number'    => '신분증 / 여권 번호',
    'photo'             => '사진',
    'passbook_photo'    => '통장 사진',
    'id_card_photo'     => '신분증 사진',

    // Attendance
    'attendance_date'   => '날짜',
    'attendance_type'   => '유형',
    'work_hours'        => '근무 시간',
    'overtime_hours'    => '초과근무 시간',
    'night_hours'       => '야간 근무 시간',
    'holiday_hours'     => '공휴일 근무 시간',
    'remarks'           => '비고',
    'full_day'          => '전일',
    'half_day'          => '반일',
    'absent'            => '결근',
    'paid_leave'        => '유급 휴가',
    'unpaid_leave'      => '무급 휴가',
    'add_attendance'    => '근태 추가',
    'edit_attendance'   => '근태 편집',
    'attendance_history'=> '근태 이력',
    'monthly_calendar'  => '월별 달력',

    // Payroll
    'payroll_period'    => '급여 기간',
    'basic_salary'      => '기본급',
    'overtime_pay'      => '초과근무 수당',
    'night_allowance'   => '야간 수당',
    'holiday_pay'       => '공휴일 수당',
    'sunday_bonus'      => '일요일 보너스',
    'gross_salary'      => '총 급여',
    'tax_deduction'     => '세금 공제',
    'advance_deduction' => '선급금 공제',
    'unpaid_deduction'  => '무급 휴가 공제',
    'total_deductions'  => '총 공제액',
    'net_salary'        => '실수령액',
    'due_salary'        => '미지급 급여',
    'generate_payroll'  => '급여 생성',
    'approve_payroll'   => '급여 승인',
    'unlock_payroll'    => '급여 잠금 해제',
    'paysheet'          => '급여 명세서',
    'draft'             => '초안',
    'approved'          => '승인됨',
    'paid'              => '지급됨',
    'payment_date'      => '지급일',
    'payment_method'    => '지급 방법',
    'bank_transfer'     => '은행 이체',

    // Advances
    'salary_advance'    => '급여 선지급',
    'advance_amount'    => '선지급 금액',
    'advance_date'      => '선지급 날짜',
    'advance_reason'    => '사유',
    'add_advance'       => '선지급 추가',

    // Reports
    'employee_report'   => '직원 보고서',
    'attendance_report' => '근태 보고서',
    'payroll_report'    => '급여 보고서',
    'tax_report'        => '세금 보고서',
    'overtime_report'   => '초과근무 보고서',
    'monthly_summary'   => '월별 급여 요약',
    'advance_report'    => '선급금 보고서',

    // Settings
    'company_settings'  => '회사 설정',
    'payroll_settings'  => '급여 설정',
    'language_settings' => '언어 설정',
    'overtime_rate'     => '초과근무 요율',
    'holiday_rate'      => '공휴일 요율',
    'company_name'      => '회사명',
    'company_logo'      => '회사 로고',
];
